### ISSUE TITLE
Rewriting process

### ISSUE THREAD

**Issue by NanguRepo** [NanguRepo/fessor#2]
# Rewrite
## Målet
Målet ved dette rewrite er at gøre botten meget mere overskuelig or versatil
F.eks. bliver det nemmere at tilføje nye funktioner ved bare at lave en ny python fil
## Hvordan det vil virke
`main.py` kommer til at være startprogrammet, som har 1 funktion. Nemlig at starte alle modulerne i botten. 
Her er en liste af ting, den skal kunne gøre:
- Starte alle moduler
- Kunne starte dem alle på en måde hvor de kører på en gang. `import` kommer ikke til at virke, fordi den kører gennem hele scriptet (tror jeg, det skal testes)
- Give output og debugging
## To-Do liste
Alt på denne liste udføres i `rewrite` branchen
- [x] Funktioner uddelt i hver deres filer og mapper (f.eks. `/school/viggo.py` eller `/fun/slander.py`
- [x] Find metode til at køre adskillige scripts på en gang
- [x] Funktionel `main.py`
- [x] Gaming

**Comment by NanguRepo** [comment]
Update:

`main.py` bliver taklet anderledes. Den kommer til at være en form for kontrollør og parser, som interpreterer alle kommandoer og caller de rigtige funktioner. Derfor er det nye approach:

- [] Deez

**Comment by NanguRepo** [comment]
Features som skal addes:
- [ ] Lock/unlock
- [ ] Settings
- [ ] Bury
- [ ] Poggers
- [ ] Badass
- [ ] Slander
- [ ] Lektiescanner
- [ ] Next
- [ ] Fuld schedule manager
- [ ] Moderation

**Comment by NanguRepo** [comment]
Efter dette skal alt lortet opgraderes
Gør følgende i kronologisk rækkefølge:
- [ ] Når alle features fra den gamle bot er med i `rewrite`, merge `main` branch og `rewrite` branch, så den gamle version ikke bliver brugt mere
- [ ] Udvid lektiescanner med søgning osv.
- [ ] Merge `Next` kommandoen med den fulde schedule manager for at lave en stor `overview` kommando
- [ ] Erstat Dynos features så den ikke skal bruges mere
- [ ] Party system
- [ ] Lektie kontributions leaderboard
- [ ] Music player
- [ ] Lav suggestions kommando så man har nyt lort at lave

**Comment by NanguRepo** [comment]
Dette issue er ikke længere krævet
